# Generated by Django 4.2.30 on 2026-04-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(db_index=True, max_length=20)),
                ('stock_name', models.CharField(max_length=100)),
                ('market', models.CharField(choices=[('A_STOCK', 'A股'), ('HK_STOCK', '港股')], max_length=10)),
                ('direction', models.CharField(choices=[('BUY', '买入'), ('SELL', '卖出')], max_length=4)),
                ('price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('quantity', models.IntegerField()),
                ('commission', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('stamp_duty', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('other_fees', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('trade_time', models.DateTimeField(db_index=True)),
                ('source', models.CharField(choices=[('THS', '同花顺'), ('HSBC_EMAIL', '汇丰邮件'), ('MANUAL', '手动录入')], max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-trade_time'],
                'unique_together': {('stock_code', 'trade_time', 'direction', 'quantity', 'price')},
            },
        ),
    ]
