# Generated by Django 4.2.30 on 2026-04-27 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeIntentSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setup_tags', models.JSONField(blank=True, default=list)),
                ('setup_notes', models.CharField(blank=True, max_length=200)),
                ('market_context_tags', models.JSONField(blank=True, default=list)),
                ('market_context_notes', models.CharField(blank=True, max_length=200)),
                ('security_quality_tags', models.JSONField(blank=True, default=list)),
                ('security_quality_notes', models.CharField(blank=True, max_length=200)),
                ('execution_emotion_tags', models.JSONField(blank=True, default=list)),
                ('execution_emotion_notes', models.CharField(blank=True, max_length=200)),
                ('planned_holding_period', models.CharField(blank=True, max_length=20)),
                ('planned_stop_loss_type', models.CharField(blank=True, max_length=30)),
                ('planned_stop_loss_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('planned_take_profit_type', models.CharField(blank=True, max_length=30)),
                ('planned_take_profit_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trade_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intent_snapshot', to='trades.traderecord')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
    ]
