# Generated by Django 4.2.30 on 2026-04-28 04:08

from django.db import migrations, models


def merge_notes_into_overall(apps, schema_editor):
    TradeIntentSnapshot = apps.get_model("trades", "TradeIntentSnapshot")
    for snapshot in TradeIntentSnapshot.objects.all():
        parts = [
            str(getattr(snapshot, "setup_notes", "") or "").strip(),
            str(getattr(snapshot, "market_context_notes", "") or "").strip(),
            str(getattr(snapshot, "security_quality_notes", "") or "").strip(),
            str(getattr(snapshot, "execution_emotion_notes", "") or "").strip(),
        ]
        merged = "；".join(part for part in parts if part)
        snapshot.overall_notes = merged
        snapshot.save(update_fields=["overall_notes"])


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ("trades", "0002_tradeintentsnapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradeintentsnapshot",
            name="overall_notes",
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.RunPython(merge_notes_into_overall, noop_reverse),
        migrations.RemoveField(
            model_name="tradeintentsnapshot",
            name="execution_emotion_notes",
        ),
        migrations.RemoveField(
            model_name="tradeintentsnapshot",
            name="market_context_notes",
        ),
        migrations.RemoveField(
            model_name="tradeintentsnapshot",
            name="security_quality_notes",
        ),
        migrations.RemoveField(
            model_name="tradeintentsnapshot",
            name="setup_notes",
        ),
    ]
