# Generated by Django 4.2.30 on 2026-05-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trades", "0003_remove_tradeintentsnapshot_execution_emotion_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="traderecord",
            name="external_trade_id",
            field=models.CharField(blank=True, db_index=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="traderecord",
            name="fee_details",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="traderecord",
            name="source",
            field=models.CharField(
                choices=[
                    ("THS", "同花顺"),
                    ("HSBC_EMAIL", "汇丰邮件"),
                    ("FUTU_API", "富途接口"),
                    ("MANUAL", "手动录入"),
                ],
                max_length=12,
            ),
        ),
    ]
