[pytest]
DJANGO_SETTINGS_MODULE = stock_trading.config.settings
addopts = -p no:cacheprovider
pythonpath =
    .
    stock_trading
python_files = test_*.py *_tests.py
testpaths =
    stock_trading
    tests
