# Generated by Django 4.2.30 on 2026-04-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(db_index=True, max_length=20)),
                ('stock_name', models.CharField(max_length=100)),
                ('market', models.CharField(choices=[('A_STOCK', 'A股'), ('HK_STOCK', '港股')], max_length=10)),
                ('quantity', models.IntegerField(default=0)),
                ('cost_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('weighted_avg_cost', models.DecimalField(decimal_places=4, max_digits=12)),
                ('total_invested', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('realized_pnl', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('ACTIVE', '持仓中'), ('CLEARED', '已清仓')], default='ACTIVE', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PositionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=20)),
                ('stock_name', models.CharField(max_length=100)),
                ('market', models.CharField(choices=[('A_STOCK', 'A股'), ('HK_STOCK', '港股')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('cost_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('entry_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
