# Generated by Django 4.2.30 on 2026-04-21 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_analysis', models.JSONField()),
                ('chip_analysis', models.JSONField()),
                ('trend_analysis', models.JSONField()),
                ('score', models.IntegerField()),
                ('suggestions', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trade_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='trades.traderecord')),
            ],
        ),
    ]
