# Generated by Django 4.2.30 on 2026-04-27 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_tradeintentsnapshot'),
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewreport',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AddField(
            model_name='reviewreport',
            name='coach_report_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reviewreport',
            name='engine_version',
            field=models.CharField(default='llm_review_v1', max_length=50),
        ),
        migrations.AddField(
            model_name='reviewreport',
            name='evidence_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reviewreport',
            name='intent_gap_diagnosis',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reviewreport',
            name='intent_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reviewreport',
            name='is_latest',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reviewreport',
            name='objective_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reviewreport',
            name='overall_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reviewreport',
            name='report_kind',
            field=models.CharField(default='llm_coach', max_length=20),
        ),
        migrations.AddField(
            model_name='reviewreport',
            name='subscores',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reviewreport',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reviewreport',
            name='chip_analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='reviewreport',
            name='trade_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_reports', to='trades.traderecord'),
        ),
        migrations.AlterField(
            model_name='reviewreport',
            name='trend_analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='reviewreport',
            name='volume_analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterUniqueTogether(
            name='reviewreport',
            unique_together={('trade_record', 'version')},
        ),
        migrations.RemoveField(
            model_name='reviewreport',
            name='score',
        ),
        migrations.RemoveField(
            model_name='reviewreport',
            name='suggestions',
        ),
    ]
