# Generated by Django 4.2.30 on 2026-04-21 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(db_index=True, max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('source', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('ANNOUNCEMENT', '公告'), ('SENTIMENT', '舆情'), ('RESEARCH', '研报'), ('INDUSTRY', '行业动态')], max_length=15)),
                ('summary', models.TextField(blank=True)),
                ('url', models.URLField(max_length=1000)),
                ('pushed', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_at'],
                'unique_together': {('title', 'source')},
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('TELEGRAM', 'Telegram'), ('WECHAT', '微信'), ('EMAIL', '邮件')], max_length=10)),
                ('status', models.CharField(choices=[('SUCCESS', '成功'), ('FAILED', '失败'), ('PENDING', '待发送')], default='PENDING', max_length=8)),
                ('retry_count', models.IntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('news_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='news.newsitem')),
            ],
        ),
    ]
